language: node_js

node_js:
  - '7.6'

install:
  - npm install

script:
  - npm test

services:
  - mongodb

# Send coverage data to Coveralls
after_script: 'cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'
